# Generated by Django 4.2.5 on 2023-09-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_Image',
            new_name='product_Image1',
        ),
        migrations.AddField(
            model_name='product',
            name='product_Image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Image5',
            field=models.ImageField(blank=True, null=True, upload_to='product_Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Image6',
            field=models.ImageField(blank=True, null=True, upload_to='product_Images'),
        ),
    ]
