# Generated by Django 4.2.5 on 2023-09-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_product_image_product_product_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
