# Generated by Django 4.2.5 on 2023-09-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Sub_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
