# Generated by Django 4.2.5 on 2023-09-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_product_sub_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=200)),
                ('product_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('product_Sub_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('product_Details', models.TextField(blank=True, null=True)),
                ('product_Price', models.CharField(max_length=50)),
                ('product_Image1', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image2', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image3', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image4', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image5', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image6', models.ImageField(blank=True, null=True, upload_to='product_Images')),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=200)),
                ('product_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('product_Sub_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('product_Details', models.TextField(blank=True, null=True)),
                ('product_Price', models.CharField(max_length=50)),
                ('product_Image1', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image2', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image3', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image4', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image5', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image6', models.ImageField(blank=True, null=True, upload_to='product_Images')),
            ],
        ),
        migrations.CreateModel(
            name='SkinCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=200)),
                ('product_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('product_Sub_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('product_Details', models.TextField(blank=True, null=True)),
                ('product_Price', models.CharField(max_length=50)),
                ('product_Image1', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image2', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image3', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image4', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image5', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image6', models.ImageField(blank=True, null=True, upload_to='product_Images')),
            ],
        ),
        migrations.RenameModel(
            old_name='product',
            new_name='HairCare',
        ),
    ]
