# Generated by Django 4.2.5 on 2023-09-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_makeup_perfume_skincare_rename_product_haircare'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Makeup',
            new_name='product',
        ),
        migrations.DeleteModel(
            name='HairCare',
        ),
        migrations.DeleteModel(
            name='Perfume',
        ),
        migrations.DeleteModel(
            name='SkinCare',
        ),
    ]
