# Generated by Django 4.2.5 on 2023-09-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_makeup_product_delete_haircare_delete_perfume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='featuedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=200)),
                ('product_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('product_Sub_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('product_Details', models.TextField(blank=True, null=True)),
                ('product_Price', models.CharField(max_length=50)),
                ('product_Image1', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image2', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image3', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image4', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image5', models.ImageField(blank=True, null=True, upload_to='product_Images')),
                ('product_Image6', models.ImageField(blank=True, null=True, upload_to='product_Images')),
            ],
        ),
    ]
